### PR TITLE
feat(Dev-517): update your wallet styling

### PR DESCRIPTION
**Pull request by ludapops**
Update your wallet modal and recent transaction styling

Screenshot 2023-03-02 at 12 06 05 PM
Screenshot 2023-03-02 at 12 21 26 PM

### CODE REVIEW

**Review by vertotrade — APPROVED** [review]
LGTM

**Comment by vertotrade** [comment]
Can you also do a search and replace for all  `headerBackground="gradientCardHeader"` in the modal components with `headerBackground="backgroundAlt"` so we don't have the gradient on any modals?

**Review by vertotrade — CHANGES_REQUESTED** [review]
Change the grandientBackground on all modals

**Comment by ludapops** [comment]
updated all gradient headers

**Review by vertotrade — APPROVED** [review]
LGTM

**Pull request merged**
