### PR TITLE
DEV-739 Update hover for tab menu items

### PR DESCRIPTION
**Pull request by phoenix377**
Updates the hover behavior for the sub-menu items. 
It adds a background color with an animation.
[DEV-739](https://rebustoken.atlassian.net/browse/DEV-739?atlOrigin=eyJpIjoiMDg0NWNmZWU3MjE5NDgwN2E2ZmU2YmRlOTMwYWZmOTkiLCJwIjoiaiJ9)

Before:

https://github.com/vertotrade/verto.ui/assets/14368843/61480b5b-d1b8-431b-a671-692fa7846337

https://github.com/vertotrade/verto.ui/assets/14368843/987555f4-5fdb-41bd-9d2b-6e7190a4de60

After:

https://github.com/vertotrade/verto.ui/assets/14368843/f3316ff1-6dac-4801-85f4-5e7b510da6ed

https://github.com/vertotrade/verto.ui/assets/14368843/5a98d360-fc18-4c0c-85ec-da502f4f8666

### CODE REVIEW

**Review by vertotrade — APPROVED** [review]
LGTM

**Review by yuushazen — APPROVED** [review]

**Comment by phoenix377** [comment]
I need to add testing scripts.

**Review by vertotrade — CHANGES_REQUESTED** [review]
Please point this PR to the nft epic

**Review by yuushazen — CHANGES_REQUESTED** [review]
Please do PRs against the NFT marketplace epic branch

**Pull request closed without merging**
