### PR TITLE
Feat/dev 523

### PR DESCRIPTION
**Pull request by boogiecyclon**
Restyling the NFT Activity page.
Screenshot 2023-03-06 at 11 09 48 AM
Screenshot 2023-03-06 at 11 10 03 AM
Screenshot 2023-03-06 at 11 10 31 AM

### CODE REVIEW

**Review by cmdnotfound — APPROVED** [review]
LGTM

**Review by nicolam1 — CHANGES_REQUESTED** [review]
This branch cannot be merged to main

**Comment by boogiecyclon** [comment]
@vertotrade @cmdnotfound @nicolam1 this PR has been retargeted to an epic branch created by @ludapops

**Review by vertotrade — APPROVED** [review]
LGTM

**Pull request merged**
