### PR TITLE
DEV-779, DEV- 781: fix loading spinner on checkout, display gas price

### PR DESCRIPTION
**Pull request by DianaSah**
DEV-779: fix loading spinner on checkout
DEV- 781: display gas price when buying NFT

Deprecated:
Screenshot 2024-01-04 at 6 00 09 PM

UPD (with new Spinner):
Screenshot 2024-01-09 at 11 03 29 AM

### CODE REVIEW

**Review by cmdnotfound — APPROVED** [review]
LGTM

**Comment by vertotrade** [comment]
@DianaSah can you test it and see if it renders ok?

**Comment by DianaSah** [comment]
> @DianaSah can you test it and see if it renders ok?

Updated PR to work with new Spinner (see description)

**Review by vertotrade — APPROVED** [review]
LGTM

**Pull request merged**
