### PR TITLE
DEV-824 Updates to the SetStagePrice Max and Min

### PR DESCRIPTION
**Pull request by Linetes**
Description

Remove the maximum price or set it pretty high, something like 20M  tokens

Minimum we can use 1

### CODE REVIEW

**Review by Kimmyyoung — APPROVED** [review]
LGTM

**Review by cmdnotfound — DISMISSED** [review]
LGTM

**Review by cmdnotfound — APPROVED** [review]
LGTM

**Review by Kimmyyoung — DISMISSED** [review]
Good work! Translation 👍

**Review by Kimmyyoung — APPROVED** [review]
LGTM

**Review by cmdnotfound — APPROVED** [review]
LGTM

**Pull request merged**
